module.exports=(sequelize,DataTypes)=>sequelize.define(
  'users',
  {
    id:{
      type:DataTypes.INTEGER,
      primaryKey:true,
      autoIncrement:true,
      allowNull:false,
    },
    nick_name:DataTypes.STRING,
    avatar_url:DataTypes.STRING,
    gender:DataTypes.STRING,
    open_id:DataTypes.STRING,
    session_key:DataTypes.STRING,
  },
  {
    tableName:'users',
  }
)
